version: "3.9"

services:
  postgis:
    image: kartoza/postgis:latest
    container_name: postgis
    volumes:
      - ./sqlscripts:/sqlscripts
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    
